name: memory
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.1.1 <4.0.0'

dependencies:
  animated_flip_card: ^1.0.2
  cloud_firestore: ^4.12.0
  firebase_auth: ^4.12.0
  firebase_core: ^2.20.0
  firebase_storage: ^11.4.0
  flippy: ^0.1.1
  flutter:
    sdk: flutter
  path: ^1.8.0
  flutter_image_compress: ^2.0.4
  flutter_riverpod: ^2.4.5
  flutter_svg: ^2.0.8
  font_awesome_flutter: ^10.6.0
  image_picker: ^1.0.4
  json_annotation: ^4.8.1
  path_provider: ^2.1.1
  sqflite: ^2.3.0
  uuid: ^4.1.0
  yaml: ^3.1.2
  sqflite_common_ffi: ^2.3.0+2
  transparent_image: ^2.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.4.6
  json_serializable: ^6.7.1

flutter:
  uses-material-design: true
  assets:
    - assets/images/cards_icon.svg
    # - assets/images/resized/03A3D74FD28543A8869F3CEF3CEDA702.jpg
    # - assets/images/resized/0870136AF5EF48A1A8DDF691446D77FB.jpg
    # - assets/images/resized/0F24B3AF97C44EF88377F32C7DEC80F0.jpg
    # - assets/images/resized/112B685DBF7449D185FCF7BBB125A8CA.jpg
    # - assets/images/resized/1C2ADB1E18CC427AB1E64025FCFDC982.jpg
    # - assets/images/resized/20A6A1A9D5FB4EAEBB831A890D216162.jpg
    # - assets/images/resized/27B71F7C7B484981ACD28C3F88697C28.jpg
    # - assets/images/resized/29926EF8A021447F83D15AA39F0CB1E1.jpg
    # - assets/images/resized/2AD09244A8D64CF7943C20E19241EC9F.jpg
    # - assets/images/resized/2F03C198D59F4F9A93268F9E46EB0B8E.jpg
    # - assets/images/resized/3863FC81B6A64B959857C709E0DB49C7.jpg
    # - assets/images/resized/46FADC4BE83B4B9595527584C7B0720C.jpg
    # - assets/images/resized/551D10B937114EDCB39D9327B969D194.jpg
    # - assets/images/resized/5722C6DF4DAA4E55AA82DA81E9CDD50C.jpg
    # - assets/images/resized/633C1FF834A842A08199947380EC7627.jpg
    # - assets/images/resized/65BE3712EFF8414CB63E8EF8B1746B33.jpg
    # - assets/images/resized/859A00C6D9D646C58BF8D44DB27BE2B5.jpg
    # - assets/images/resized/989BEE96830F40A6A3DA30D193133E2B.jpg
    # - assets/images/resized/9F8792B4CBAD4541A71D9442813E8121.jpg
    # - assets/images/resized/AC3D6424D18E40C7B7247F01102BC4B3.jpg
    # - assets/images/resized/alen_kindergarten.jpg
    # - assets/images/resized/B2FEAE986E5F46DA8DB1864760536FF9.jpg
    # - assets/images/resized/B80998A03E0245588DF04452FFA6DF89.jpg
    # - assets/images/resized/BFC90F1DF1734458A38BC3068C9A6EC2.jpg
    # - assets/images/resized/C39CCC1B7AE34C459B0EF43DBF0C773D.jpg
    # - assets/images/resized/CC306C0F7C9A4E40B1F597AD6D1A1A89.jpg
    # - assets/images/resized/CC642B7084A44795B9DDC5BE90726A1B.jpg
    # - assets/images/resized/CD9EAB7818C546B1AC82EFBEB8881FB1.jpg
    # - assets/images/resized/CE0E07F763754EBDA832C122DF3C4EB9.jpg
    # - assets/images/resized/D273B3D2FA3943CB9C5DA50A1A0FD802.jpg
    # - assets/images/resized/DA27811A4D424A8E85D8AEEA9D0563C4.jpg
    # - assets/images/resized/E144D325119A4781AC071769308865D4.jpg
    # - assets/images/resized/E7D324A9F91B4893B857C34863802A45.jpg
    # - assets/images/resized/E92639AE57B64339AA9A352F900F7566.jpg
    # - assets/images/resized/EE1C88849F0C42DDBAAC13262C6D1B34.jpg
    # - assets/images/resized/F9D9F5799455424CB80AF8BF7E5970A4.jpg
    # - assets/images/resized/jina_and_beni_0.jpg
    # - assets/images/resized/jina_and_beni_1.jpg
    # - assets/images/resized/LINE_ALBUM_20220921_일본에온날__231011_1.jpg
    # - assets/images/resized/LINE_ALBUM_20220923Mt.Aso_231011_1.jpg
    # - assets/images/resized/LINE_ALBUM_문지나시집갔다_231011_1.jpg
    # - assets/images/resized/LINE_ALBUM_문지나시집갔다_231011_4.jpg
    # - assets/images/resized/LINE_ALBUM_예준이의성장일기_231011_1.jpg
    # - assets/images/resized/Screenshot20231011102439.jpg
    # - assets/images/resized/Screenshot_20231011_210937.jpg
    # - assets/images/resized/Screenshot_20231011_211017.jpg
    # - assets/images/resized/Screenshot_20231011_211603.jpg
    # - assets/images/resized/Screenshot_20231011_211705.jpg
    # - assets/images/resized/Screenshot_20231011_211830.jpg
    # - assets/images/resized/Screenshot_20231013_012824.jpg
    # - assets/images/resized/S__40067085.jpg
    # - assets/images/resized/S__40067093.jpg
    # - assets/images/resized/S__40067104.jpg
    # - assets/images/resized/S__40067111.jpg
    # - assets/images/resized/S__40067113.jpg
    # - assets/images/resized/S__40067114.jpg
    # - assets/images/resized/S__40067119.jpg
    # - assets/images/resized/S__40067123.jpg
    # - assets/images/resized/S__40067130_0.jpg
    # - assets/images/resized/S__40067132_0.jpg
    # - assets/images/resized/S__40067134_0.jpg
    # - assets/images/resized/S__40067136_0.jpg
    # - assets/images/resized/S__40067137_0.jpg
    # - assets/images/resized/S__40067138_0.jpg
    # - assets/images/resized/S__40067139_0.jpg
    # - assets/images/resized/S__40067140_0.jpg
    # - assets/images/resized/S__40067141_0.jpg
    # - assets/images/resized/S__40067142_0.jpg
    # - assets/images/resized/S__40067143_0.jpg
    # - assets/images/resized/S__40067145_0.jpg
    # - assets/images/resized/S__40067147_0.jpg
    # - assets/images/resized/S__40067148_0.jpg
    # - assets/images/resized/S__40067149_0.jpg
    # - assets/images/resized/S__40067150_0.jpg
    # - assets/images/resized/S__40067151_0.jpg
    # - assets/images/resized/S__40067152_0.jpg
    # - assets/images/resized/S__40067153_0.jpg
    # - assets/images/resized/S__40067154_0.jpg
    # - assets/images/resized/S__40067155_0.jpg
    # - assets/images/resized/S__40067156_0.jpg
    # - assets/images/resized/S__40067158_0.jpg
    # - assets/images/resized/S__40067159_0.jpg
    # - assets/images/resized/S__40067160_0.jpg
    # - assets/images/resized/S__40067161_0.jpg
    # - assets/images/resized/S__40067162_0.jpg
    # - assets/images/resized/S__40067164.jpg
    # - assets/images/resized/S__40067164_0.jpg
    # - assets/images/resized/S__40067166_0.jpg
    # - assets/images/resized/S__40067167_0.jpg
    # - assets/images/resized/S__40067168_0.jpg
    # - assets/images/resized/S__40067169_0.jpg
    # - assets/images/resized/S__40067170_0.jpg
    # - assets/images/resized/S__40067171_0.jpg
