name: memory
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.1.1 <4.0.0'

dependencies:
  animated_flip_card: ^1.0.2
  cloud_firestore: ^4.12.0
  firebase_auth: ^4.12.0
  firebase_core: ^2.20.0
  firebase_storage: ^11.4.0
  flippy: ^0.1.1
  flutter:
    sdk: flutter
  path: ^1.8.0
  flutter_image_compress: ^2.0.4
  flutter_riverpod: ^2.4.5
  flutter_svg: ^2.0.8
  font_awesome_flutter: ^10.6.0
  image_picker: ^1.0.4
  json_annotation: ^4.8.1
  path_provider: ^2.1.1
  sqflite: ^2.3.0
  uuid: ^4.1.0
  yaml: ^3.1.2
  sqflite_common_ffi: ^2.3.0+2
  transparent_image: ^2.0.1
  flip_card: ^0.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.4.6
  json_serializable: ^6.7.1

flutter:
  uses-material-design: true
  assets:
    - assets/images/cards_icon.svg
    