name: memory
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.1.1 <4.0.0'

dependencies:
  animated_flip_card: ^1.0.2
  flippy: ^0.1.1
  flutter:
    sdk: flutter
  flutter_image_compress: ^2.0.4
  flutter_riverpod: ^2.4.3
  yaml: ^3.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/alen_kindergarten.jpg
    - assets/images/jina_and_beni_0.png
    - assets/images/jina_and_beni_1.png
    - assets/images/LINE_ALBUM_20220921_일본에온날__231011_1.jpg
    - assets/images/LINE_ALBUM_20220923Mt.Aso_231011_1.jpg
    - assets/images/LINE_ALBUM_문지나시집갔다_231011_1.jpg
    - assets/images/LINE_ALBUM_문지나시집갔다_231011_4.jpg
    - assets/images/LINE_ALBUM_예준이의성장일기_231011_1.jpg
    - assets/images/Screenshot20231011102439.png
    - assets/images/Screenshot_20231011_210937.png
    - assets/images/Screenshot_20231011_211017.png
    - assets/images/Screenshot_20231011_211603.png
    - assets/images/Screenshot_20231011_211705.png
    - assets/images/Screenshot_20231011_211830.png
    - assets/images/S__40067085.jpg
    - assets/images/S__40067093.jpg
    - assets/images/S__40067104.jpg
    - assets/images/S__40067111.jpg
    - assets/images/S__40067113.jpg
    - assets/images/S__40067114.jpg
    - assets/images/S__40067119.jpg
    - assets/images/S__40067123.jpg
    - assets/images/S__40067130_0.jpg
    - assets/images/S__40067132_0.jpg
    - assets/images/S__40067134_0.jpg
    - assets/images/S__40067136_0.jpg
    - assets/images/S__40067137_0.jpg
    - assets/images/S__40067138_0.jpg
    - assets/images/S__40067139_0.jpg
    - assets/images/S__40067140_0.jpg
    - assets/images/S__40067141_0.jpg
    - assets/images/S__40067142_0.jpg
    - assets/images/S__40067143_0.jpg
    - assets/images/S__40067145_0.jpg
    - assets/images/S__40067147_0.jpg
    - assets/images/S__40067148_0.jpg
    - assets/images/S__40067149_0.jpg
    - assets/images/S__40067150_0.jpg
    - assets/images/S__40067151_0.jpg
    - assets/images/S__40067152_0.jpg
    - assets/images/S__40067153_0.jpg
    - assets/images/S__40067154_0.jpg
    - assets/images/S__40067155_0.jpg
    - assets/images/S__40067156_0.jpg
    - assets/images/S__40067158_0.jpg
    - assets/images/S__40067159_0.jpg
    - assets/images/S__40067160_0.jpg
    - assets/images/S__40067161_0.jpg
    - assets/images/S__40067162_0.jpg
    - assets/images/S__40067164.jpg
    - assets/images/S__40067164_0.jpg
    - assets/images/S__40067166_0.jpg
    - assets/images/S__40067167_0.jpg
    - assets/images/S__40067168_0.jpg
    - assets/images/S__40067169_0.jpg
    - assets/images/S__40067170_0.jpg
    - assets/images/S__40067171_0.jpg
